### PR TITLE
fix: lower maximum fee placeholder because of Paris max gas limit change

### LINKED ISSUE #44: Bug: Maximum Gas Fee Limit Exceeded Due to Tezos Paris Upgrade
#### **Description**
The recent Tezos Paris upgrade has introduced changes that affect the calculation of the maximum gas fee limit. This issue is causing transactions to exceed the previously established gas fee cap, leading to unexpected failures in our application.

#### **Impact**
- Users are experiencing failed transactions due to the new gas fee limits.
- This issue is critical as it directly affects the usability and reliability of the dapp.

#### **Error Details**
The following error is encountered when attempting to preview a transaction:
```json
[
    {
        "kind": "permanent",
        "id": "proto.020-PsParisC.gas_limit_too_high"
    },
    {
        "kind": "temporary",
        "id": "proto.020-PsParisC.gas_exhausted.block"
    }
]
```

#### **Steps to Reproduce**
1. Perform a transaction post-Tezos Paris upgrade.
2. Observe the gas fee calculation.
3. Notice the transaction failure if the gas fee exceeds the limit.

#### **Expected Behavior**
Transactions pop-up should appear.

#### **Actual Behavior**
Transactions are failing because the maximum gas fee exceeds the previously established maximum limit.

<p align="center">
    <video src="https://github.com/user-attachments/assets/fa965c98-e43b-42c8-bd8f-4128c4e2fd00">
    <br>
</p>

### PR DESCRIPTION
**Pull request by khanti42**
Closes #44 

<p align="center">
    <video src="https://github.com/user-attachments/assets/2ed86060-0bb3-45f6-98d4-3245b0318eab">
</p>

Still failing because maximum gas limit has to been changed in the snap as well: https://github.com/airgap-it/tezos-metamask-snap

### CODE REVIEW

**Comment by mattgale33** [comment]
Same error after fix

**Review by mattgale33 — APPROVED** [review]

**Comment by khanti42** [comment]
Done, I also tested locally and I can get the fee estimation correctly. @AndreasGassmann can you review the changes ?

**Comment by AndreasGassmann** [comment]
@khanti42 Thanks, merged!

**Comment by mattgale33** [comment]
How long before the Fix goes live? Still not working as of 1010 21/08/2024

**Comment by khanti42** [comment]
@mattgale33 In order for this fix to go live it needs both this repo and the snaps repo [here](https://github.com/airgap-it/tezos-metamask-snap/pull/20) to have the fixed merged. 

The snaps update after the pull request has been merged and the npm repository updated with the latest version it can still take 1-2 days, as we need to review the changes of the snaps and allow list the new version. We will comment in and close the associated issue when the fix is live so that you can test it and confirm if it solves your issue.

**Comment by mattgale33** [comment]
OK, Thank you for the updatand help getting this fixed!!

**Pull request merged**
